import React, { useState } from 'react';
import { X, Sparkles, GitBranch, MessageSquare, Zap, FileText, Brain, Code2, TrendingUp } from 'lucide-react';
import { useTheme } from '../ThemeContext';
import { cn } from './ui';
import { CustomNode } from '../types';
import { Edge } from '@xyflow/react';

interface Template {
  id: string;
  name: string;
  description: string;
  icon: any;
  color: string;
  category: string;
  nodes: CustomNode[];
  edges: Edge[];
}

const TEMPLATES: Template[] = [
  {
    id: 'chatbot',
    name: 'AI Chatbot',
    description: 'Simple chatbot with input, AI processing, and output',
    icon: MessageSquare,
    color: 'from-emerald-400 to-green-500',
    category: 'AI',
    nodes: [
      { id: 'input-1', type: 'io', position: { x: 100, y: 200 }, data: { label: 'Chat Input', type: 'io', subType: 'Chat Input', config: { placeholder: 'Ask me anything...' } } },
      { id: 'ai-1', type: 'ai', position: { x: 400, y: 200 }, data: { label: 'Gemini', type: 'ai', subType: 'Gemini', config: { model: 'gemini-2.5-flash-lite', systemPrompt: 'You are a helpful assistant.', temperature: 0.7 } } },
      { id: 'output-1', type: 'io', position: { x: 700, y: 200 }, data: { label: 'Output', type: 'io', subType: 'Output', config: { outputFormat: 'Markdown' } } },
    ],
    edges: [
      { id: 'e1-2', source: 'input-1', target: 'ai-1', animated: true },
      { id: 'e2-3', source: 'ai-1', target: 'output-1', animated: true },
    ],
  },
  {
    id: 'content-pipeline',
    name: 'Content Pipeline',
    description: 'Generate and transform content with templates',
    icon: FileText,
    color: 'from-violet-400 to-purple-500',
    category: 'Content',
    nodes: [
      { id: 'trigger-1', type: 'timer', position: { x: 100, y: 200 }, data: { label: 'Manual Trigger', type: 'timer', subType: 'Manual', config: {} } },
      { id: 'ai-1', type: 'ai', position: { x: 350, y: 200 }, data: { label: 'Content Generator', type: 'ai', subType: 'Gemini', config: { model: 'gemini-2.5-flash-lite', systemPrompt: 'Generate creative content based on the topic.', temperature: 0.9 } } },
      { id: 'template-1', type: 'template', position: { x: 600, y: 200 }, data: { label: 'Format Output', type: 'template', config: { template: '# {{title}}\n\n{{content}}\n\n---\nGenerated by FlowCraft' } } },
      { id: 'output-1', type: 'io', position: { x: 850, y: 200 }, data: { label: 'Output', type: 'io', subType: 'Output', config: {} } },
    ],
    edges: [
      { id: 'e1-2', source: 'trigger-1', target: 'ai-1', animated: true },
      { id: 'e2-3', source: 'ai-1', target: 'template-1', animated: true },
      { id: 'e3-4', source: 'template-1', target: 'output-1', animated: true },
    ],
  },
  {
    id: 'conditional-flow',
    name: 'Smart Router',
    description: 'Route data based on conditions with branching logic',
    icon: GitBranch,
    color: 'from-yellow-400 to-orange-500',
    category: 'Logic',
    nodes: [
      { id: 'input-1', type: 'io', position: { x: 100, y: 250 }, data: { label: 'Input', type: 'io', subType: 'Chat Input', config: {} } },
      { id: 'cond-1', type: 'conditional', position: { x: 350, y: 250 }, data: { label: 'Check Score', type: 'conditional', config: { condition: 'data.score >= 0.7' } } },
      { id: 'ai-high', type: 'ai', position: { x: 600, y: 150 }, data: { label: 'High Quality', type: 'ai', subType: 'Gemini', config: { systemPrompt: 'Process high-quality input' } } },
      { id: 'ai-low', type: 'ai', position: { x: 600, y: 350 }, data: { label: 'Low Quality', type: 'ai', subType: 'Gemini', config: { systemPrompt: 'Handle low-quality input with extra care' } } },
      { id: 'output-1', type: 'io', position: { x: 850, y: 250 }, data: { label: 'Output', type: 'io', subType: 'Output', config: {} } },
    ],
    edges: [
      { id: 'e1-2', source: 'input-1', target: 'cond-1', animated: true },
      { id: 'e2-3', source: 'cond-1', target: 'ai-high', sourceHandle: 'true', animated: true },
      { id: 'e2-4', source: 'cond-1', target: 'ai-low', sourceHandle: 'false', animated: true },
      { id: 'e3-5', source: 'ai-high', target: 'output-1', animated: true },
      { id: 'e4-5', source: 'ai-low', target: 'output-1', animated: true },
    ],
  },
  {
    id: 'code-processor',
    name: 'Code Processor',
    description: 'Transform data with custom Python code',
    icon: Code2,
    color: 'from-lime-400 to-green-500',
    category: 'Data',
    nodes: [
      { id: 'trigger-1', type: 'timer', position: { x: 100, y: 200 }, data: { label: 'Manual Trigger', type: 'timer', subType: 'Manual', config: {} } },
      { id: 'code-1', type: 'code', position: { x: 350, y: 200 }, data: { label: 'Transform Data', type: 'code', config: { language: 'Python', code: '# Transform input data\ndata = input.get("data", [])\nresult = [item * 2 for item in data if isinstance(item, (int, float))]' } } },
      { id: 'output-1', type: 'io', position: { x: 600, y: 200 }, data: { label: 'Output', type: 'io', subType: 'Output', config: {} } },
    ],
    edges: [
      { id: 'e1-2', source: 'trigger-1', target: 'code-1', animated: true },
      { id: 'e2-3', source: 'code-1', target: 'output-1', animated: true },
    ],
  },
  {
    id: 'webhook-handler',
    name: 'Webhook Handler',
    description: 'Process incoming webhooks with AI',
    icon: Zap,
    color: 'from-pink-400 to-fuchsia-500',
    category: 'Integration',
    nodes: [
      { id: 'webhook-1', type: 'webhook', position: { x: 100, y: 200 }, data: { label: 'Webhook', type: 'webhook', config: { method: 'POST', endpoint: '/api/webhook/incoming' } } },
      { id: 'ai-1', type: 'ai', position: { x: 350, y: 200 }, data: { label: 'Process Payload', type: 'ai', subType: 'Gemini', config: { systemPrompt: 'Extract and summarize the key information from this webhook payload.' } } },
      { id: 'notify-1', type: 'notification', position: { x: 600, y: 200 }, data: { label: 'Send Alert', type: 'notification', config: { channel: 'Slack', message: 'New webhook processed!' } } },
    ],
    edges: [
      { id: 'e1-2', source: 'webhook-1', target: 'ai-1', animated: true },
      { id: 'e2-3', source: 'ai-1', target: 'notify-1', animated: true },
    ],
  },
  {
    id: 'multi-model',
    name: 'Multi-Model Ensemble',
    description: 'Compare outputs from multiple AI models',
    icon: Brain,
    color: 'from-amber-400 to-orange-500',
    category: 'AI',
    nodes: [
      { id: 'input-1', type: 'io', position: { x: 100, y: 300 }, data: { label: 'Input', type: 'io', subType: 'Chat Input', config: {} } },
      { id: 'ai-gemini', type: 'ai', position: { x: 350, y: 150 }, data: { label: 'Gemini', type: 'ai', subType: 'Gemini', config: { model: 'gemini-2.5-flash-lite' } } },
      { id: 'ai-claude', type: 'ai', position: { x: 350, y: 300 }, data: { label: 'Claude', type: 'ai', subType: 'Claude', config: { model: 'claude-4-sonnet' } } },
      { id: 'ai-gpt', type: 'ai', position: { x: 350, y: 450 }, data: { label: 'GPT-4', type: 'ai', subType: 'OpenAI', config: { model: 'gpt-4o' } } },
      { id: 'template-1', type: 'template', position: { x: 600, y: 300 }, data: { label: 'Combine Results', type: 'template', config: { template: '## Model Comparison\n\n**Gemini:** {{gemini}}\n\n**Claude:** {{claude}}\n\n**GPT-4:** {{gpt4}}' } } },
      { id: 'output-1', type: 'io', position: { x: 850, y: 300 }, data: { label: 'Output', type: 'io', subType: 'Output', config: {} } },
    ],
    edges: [
      { id: 'e1-2', source: 'input-1', target: 'ai-gemini', animated: true },
      { id: 'e1-3', source: 'input-1', target: 'ai-claude', animated: true },
      { id: 'e1-4', source: 'input-1', target: 'ai-gpt', animated: true },
      { id: 'e2-5', source: 'ai-gemini', target: 'template-1', animated: true },
      { id: 'e3-5', source: 'ai-claude', target: 'template-1', animated: true },
      { id: 'e4-5', source: 'ai-gpt', target: 'template-1', animated: true },
      { id: 'e5-6', source: 'template-1', target: 'output-1', animated: true },
    ],
  },
  {
    id: 'ml-random-forest',
    name: 'Random Forest Pipeline',
    description: 'CSV → Data Prep → Feature Engineering → Random Forest → Evaluation',
    icon: TrendingUp,
    color: 'from-emerald-400 to-teal-500',
    category: 'ML',
    nodes: [
      { id: 'input-1', type: 'file_upload', position: { x: 50, y: 280 }, data: { label: 'Upload CSV', type: 'file_upload', config: {} } },
      { id: 'fill-1', type: 'data_prep', position: { x: 300, y: 280 }, data: { label: 'Fill Missing', type: 'data_prep', subType: 'FillMissing', config: { algorithm: 'FillMissing', strategy: 'mean' } } },
      { id: 'encode-1', type: 'data_prep', position: { x: 550, y: 280 }, data: { label: 'Label Encode', type: 'data_prep', subType: 'Encode', config: { algorithm: 'Encode' } } },
      { id: 'normalize-1', type: 'data_prep', position: { x: 800, y: 280 }, data: { label: 'Normalize', type: 'data_prep', subType: 'Normalize', config: { algorithm: 'Normalize' } } },
      { id: 'split-1', type: 'data_prep', position: { x: 1050, y: 280 }, data: { label: 'Train/Test Split', type: 'data_prep', subType: 'TrainTestSplit', config: { algorithm: 'TrainTestSplit', test_size: 0.2, target_column: 'target' } } },
      { id: 'rf-1', type: 'ml', position: { x: 1300, y: 280 }, data: { label: 'Random Forest', type: 'ml', subType: 'RandomForest', config: { algorithm: 'RandomForest', n_estimators: 100, max_depth: 10 } } },
      { id: 'eval-1', type: 'evaluate', position: { x: 1550, y: 280 }, data: { label: 'Evaluate', type: 'evaluate', subType: 'Auto', config: { algorithm: 'Auto' } } },
      { id: 'output-1', type: 'io', position: { x: 1800, y: 280 }, data: { label: 'Results', type: 'io', subType: 'Output', config: {} } },
    ],
    edges: [
      { id: 'e1-2', source: 'input-1', target: 'fill-1', animated: true },
      { id: 'e2-3', source: 'fill-1', target: 'encode-1', animated: true },
      { id: 'e3-4', source: 'encode-1', target: 'normalize-1', animated: true },
      { id: 'e4-5', source: 'normalize-1', target: 'split-1', animated: true },
      { id: 'e5-6', source: 'split-1', target: 'rf-1', animated: true },
      { id: 'e6-7', source: 'rf-1', target: 'eval-1', animated: true },
      { id: 'e7-8', source: 'eval-1', target: 'output-1', animated: true },
    ],
  },
  {
    id: 'ml-model-comparison',
    name: 'Model Comparison',
    description: 'Compare Random Forest, XGBoost, and SVM on the same dataset',
    icon: Brain,
    color: 'from-violet-400 to-purple-500',
    category: 'ML',
    nodes: [
      { id: 'input-1', type: 'file_upload', position: { x: 50, y: 300 }, data: { label: 'Upload Dataset', type: 'file_upload', config: {} } },
      { id: 'fill-1', type: 'data_prep', position: { x: 300, y: 300 }, data: { label: 'Fill Missing', type: 'data_prep', subType: 'FillMissing', config: { algorithm: 'FillMissing', strategy: 'mean' } } },
      { id: 'encode-1', type: 'data_prep', position: { x: 550, y: 300 }, data: { label: 'Label Encode', type: 'data_prep', subType: 'Encode', config: { algorithm: 'Encode' } } },
      { id: 'split-1', type: 'data_prep', position: { x: 800, y: 300 }, data: { label: 'Train/Test Split', type: 'data_prep', subType: 'TrainTestSplit', config: { algorithm: 'TrainTestSplit', test_size: 0.2, target_column: 'target' } } },
      { id: 'rf-1', type: 'ml', position: { x: 1100, y: 100 }, data: { label: 'Random Forest', type: 'ml', subType: 'RandomForest', config: { algorithm: 'RandomForest', n_estimators: 100 } } },
      { id: 'xgb-1', type: 'ml', position: { x: 1100, y: 300 }, data: { label: 'XGBoost', type: 'ml', subType: 'XGBoost', config: { algorithm: 'XGBoost', n_estimators: 100 } } },
      { id: 'svm-1', type: 'ml', position: { x: 1100, y: 500 }, data: { label: 'SVM', type: 'ml', subType: 'SVM', config: { algorithm: 'SVM', kernel: 'rbf' } } },
      { id: 'eval-rf', type: 'evaluate', position: { x: 1400, y: 100 }, data: { label: 'Eval RF', type: 'evaluate', subType: 'Auto', config: { algorithm: 'Auto' } } },
      { id: 'eval-xgb', type: 'evaluate', position: { x: 1400, y: 300 }, data: { label: 'Eval XGB', type: 'evaluate', subType: 'Auto', config: { algorithm: 'Auto' } } },
      { id: 'eval-svm', type: 'evaluate', position: { x: 1400, y: 500 }, data: { label: 'Eval SVM', type: 'evaluate', subType: 'Auto', config: { algorithm: 'Auto' } } },
    ],
    edges: [
      { id: 'e1-2', source: 'input-1', target: 'fill-1', animated: true },
      { id: 'e2-3', source: 'fill-1', target: 'encode-1', animated: true },
      { id: 'e3-4', source: 'encode-1', target: 'split-1', animated: true },
      { id: 'e4-rf', source: 'split-1', target: 'rf-1', animated: true },
      { id: 'e4-xgb', source: 'split-1', target: 'xgb-1', animated: true },
      { id: 'e4-svm', source: 'split-1', target: 'svm-1', animated: true },
      { id: 'erf-eval', source: 'rf-1', target: 'eval-rf', animated: true },
      { id: 'exgb-eval', source: 'xgb-1', target: 'eval-xgb', animated: true },
      { id: 'esvm-eval', source: 'svm-1', target: 'eval-svm', animated: true },
    ],
  },
];

interface TemplatesModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectTemplate: (nodes: CustomNode[], edges: Edge[], name: string) => void;
}

export const TemplatesModal: React.FC<TemplatesModalProps> = ({ isOpen, onClose, onSelectTemplate }) => {
  const { theme } = useTheme();
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [hoveredTemplate, setHoveredTemplate] = useState<string | null>(null);

  if (!isOpen) return null;

  const categories = [...new Set(TEMPLATES.map(t => t.category))];
  const filteredTemplates = selectedCategory 
    ? TEMPLATES.filter(t => t.category === selectedCategory)
    : TEMPLATES;


  

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />
      
      {/* Modal */}
      <div className={cn(
        'relative w-[800px] max-h-[80vh] rounded-3xl border shadow-2xl overflow-hidden flex flex-col',
        theme.panelBg, theme.panelBorder
      )}>
        {/* Header */}
        <div className={cn('flex items-center justify-between p-6 border-b', theme.nodeHeaderBorder)}>
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-500 shadow-lg">
              <Sparkles size={20} className="text-white" />
            </div>
            <div>
              <h2 className={cn('text-lg font-bold', theme.textPrimary)}>Workflow Templates</h2>
              <p className={cn('text-xs', theme.textMuted)}>Start with a pre-built workflow and customize it</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className={cn('p-2 rounded-xl transition-colors', theme.btnHover, theme.textMuted)}
          >
            <X size={20} />
          </button>
        </div>

        {/* Category filters */}
        <div className={cn('flex gap-2 px-6 py-4 border-b', theme.nodeHeaderBorder)}>
          <button
            onClick={() => setSelectedCategory(null)}
            className={cn(
              'px-4 py-1.5 rounded-full text-xs font-semibold transition-all',
              selectedCategory === null
                ? 'bg-blue-500 text-white'
                : cn(theme.btnBg, theme.textSecondary, theme.btnHover)
            )}
          >
            All
          </button>
          {categories.map(cat => (
            <button
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              className={cn(
                'px-4 py-1.5 rounded-full text-xs font-semibold transition-all',
                selectedCategory === cat
                  ? 'bg-blue-500 text-white'
                  : cn(theme.btnBg, theme.textSecondary, theme.btnHover)
              )}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Templates grid */}
        <div className="flex-1 overflow-y-auto p-6 custom-scrollbar">
          <div className="grid grid-cols-2 gap-4">
            {filteredTemplates.map(template => {
              const Icon = template.icon;
              const isHovered = hoveredTemplate === template.id;
              
              return (
                <button
                  key={template.id}
                  onClick={() => {
                    onSelectTemplate(template.nodes, template.edges, template.name);
                    onClose();
                  }}
                  onMouseEnter={() => setHoveredTemplate(template.id)}
                  onMouseLeave={() => setHoveredTemplate(null)}
                  className={cn(
                    'relative p-5 rounded-2xl border text-left transition-all duration-300 group overflow-hidden',
                    theme.nodeBg, theme.nodeBorder,
                    isHovered && 'scale-[1.02] shadow-xl',
                    theme.btnHover
                  )}
                >
                  {/* Glow effect */}
                  <div className={cn(
                    'absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300',
                    `bg-gradient-to-br ${template.color}`,
                    'blur-3xl -z-10'
                  )} style={{ opacity: isHovered ? 0.1 : 0 }} />
                  
                  <div className="flex items-start gap-4">
                    <div className={cn(
                      'p-3 rounded-xl bg-gradient-to-br shadow-lg transition-transform duration-300',
                      template.color,
                      isHovered && 'scale-110'
                    )}>
                      <Icon size={24} className="text-white" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h3 className={cn('font-bold mb-1', theme.textPrimary)}>{template.name}</h3>
                      <p className={cn('text-xs leading-relaxed', theme.textMuted)}>{template.description}</p>
                      <div className="flex items-center gap-2 mt-3">
                        <span className={cn(
                          'text-[10px] font-bold uppercase tracking-widest px-2 py-0.5 rounded-full',
                          theme.btnBg, theme.textMuted
                        )}>
                          {template.category}
                        </span>
                        <span className={cn('text-[10px]', theme.textMuted)}>
                          {template.nodes.length} nodes
                        </span>
                      </div>
                    </div>
                  </div>
                </button>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
};
