/**
 * testing2
 *
 * testing purpose
 *
 * Scaffold generated by the Onelign QGen mock inference provider. Configure INFERENCE_PROVIDER=ollama or vllm for model-generated implementations.
 */

export const FEATURE_KEY = "testing2";
export const FEATURE_TITLE = "testing2";

export function isEnabled(flags = {}) {
  return Boolean(flags[FEATURE_KEY] ?? true);
}

export function describe() {
  return { key: FEATURE_KEY, title: FEATURE_TITLE, enabled: isEnabled() };
}
