"""
testing_1

testing purpose

Scaffold generated by the Onelign QGen mock inference provider. Configure INFERENCE_PROVIDER=ollama or vllm for model-generated implementations.
"""

from typing import Any, Dict, Optional

FEATURE_KEY = "testing_1"
FEATURE_TITLE = "testing_1"


def is_enabled(flags: Optional[Dict[str, bool]] = None) -> bool:
    """The feature is on unless explicitly disabled via flags."""
    return bool((flags or {}).get(FEATURE_KEY, True))


def describe() -> Dict[str, Any]:
    """Machine-readable description of the feature."""
    return {"key": FEATURE_KEY, "title": FEATURE_TITLE, "enabled": is_enabled()}
